Loader for cumulative effects hotspots
ECCC-MSC/msc-pygeoapi pull request #199
Opened 2022-07-26 15:58 UTC by PhilippeTh

RAQDPS-FW Cumulative Effects Hotspots loader, data from 2013 to 2020 already added using the script.

2022-07-26 18:03 UTC, Dukestep commented
Tests failing for unrelated reasons. I do notice some long lines in there though, @PhilippeTh. Can you run `flake8`?

2022-08-05 17:02 UTC, tomkralidis requested changes

2022-08-05 17:02 UTC, tomkralidis commented on msc_pygeoapi/loader/__init__.py
> +    ('msc_pygeoapi.loader.cumulative_effects_hs', 'cumulative_effects_hs'),
remove trailing commas from of dicts/sets/tuples.

2022-08-05 17:02 UTC, tomkralidis commented on msc_pygeoapi/loader/cumulative_effects_hs.py
> +        Generates and yields a series of cumulative effects hotspots.
Put empty lines between descriptoins, params and returns

```
def foo(var1):
    """
    My foo function

    :param var1: some string

    :returns: some transformed string
    """
```

2022-08-05 17:02 UTC, tomkralidis commented on msc_pygeoapi/loader/cumulative_effects_hs.py
> +
remove empty line in this context

2022-08-05 17:02 UTC, tomkralidis commented on msc_pygeoapi/loader/cumulative_effects_hs.py
> +        """
Put empty lines between descriptoins, params and returns

```
def foo(var1):
    """
    My foo function

    :param var1: some string

    :returns: some transformed string
    """
```

2022-08-05 17:02 UTC, tomkralidis commented on msc_pygeoapi/loader/cumulative_effects_hs.py
> +        self.filepath = Path(filepath)
This should be set in the initializer (`None`) for safeguarding.

2022-08-08 11:21 UTC, PhilippeTh commented
@tomkralidis Done!

2022-08-08 14:43 UTC, tomkralidis commented
@PhilippeTh can you resolve the  merge conflicts?

2022-08-09 11:32 UTC, tomkralidis commented
@PhilippeTh yes failures are unrelated. Is this PR ready for another review then?

2022-08-09 11:33 UTC, PhilippeTh commented
@tomkralidis It is!

2022-08-09 11:35 UTC, merged