rlat and rlon reprojection
ECCC-MSC/msc-pygeoapi pull request #261
Opened 2023-04-12 12:15 UTC by adanb13

### Changes

- User provides `rlon` and `rlat` in WGS84, provider re-projects using native CRS

### Example Links
_NOTE: Need to use slight range for `rlat/rlon` as `nearest` not yet implemented_

**Toronto**
http://infopool-dev1.cmc.ec.gc.ca:5089/collections/weong:hrdps:tt/coverage?subset=rlon(-79.421371:-72),rlat(43.780918:45),level(1:1)&datetime=2023-03-09T00:00:00.000000000&f=json

**Ottawa**
http://infopool-dev1.cmc.ec.gc.ca:5089/collections/weong:hrdps:tt/coverage?subset=rlon(-75.695000:-74),rlat(43.780918:45),level(1:1)&datetime=2023-03-09T00:00:00.000000000&f=json

**Edmonton**
http://infopool-dev1.cmc.ec.gc.ca:5089/collections/weong:hrdps:tt/coverage?subset=rlon(-113.4937:-112),rlat(53.5461:54),level(1:1)&datetime=2023-03-09T00:00:00.000000000&f=json

**New Brunswick**
http://infopool-dev1.cmc.ec.gc.ca:5089/collections/weong:hrdps:tt/coverage?subset=rlon(-66.159668:-65),rlat(46.498390:47),level(1:1)&datetime=2023-03-09T00:00:00.000000000&f=json

**Prince Edward Island**
http://infopool-dev1.cmc.ec.gc.ca:5089/collections/weong:hrdps:tt/coverage?subset=rlon(-63.000000:-62),rlat(46.250000:47),level(1:1)&datetime=2023-03-09T00:00:00.000000000&f=json

**Yukon**
http://infopool-dev1.cmc.ec.gc.ca:5089/collections/weong:hrdps:tt/coverage?subset=rlon(-131.352539:-130),rlat(62.350357:63),level(1:1)&datetime=2023-03-09T00:00:00.000000000&f=json

### TO DO

- Have Shaheed confirm provider now returns data as required
- implement `nearest` method for point queries
- _(Improvement)_ implement reprojection to `bbox` queries allowing us to use `.sel` instead of `.where` which is much faster and gets rid for the need to use `eval`

2023-04-17 15:36 UTC, adanb13 commented
with reference to "time query fix": (just pushed changes that would make it so nearest also activates on an invalid datetime value, to undo and only have it activate for rlon/rlon values I would revert to the previous commit)

2023-04-25 21:34 UTC, tomkralidis requested changes

2023-04-25 21:34 UTC, tomkralidis commented on msc_pygeoapi/provider/hrdps_zarr.py
> +from pyproj import CRS, Transformer
move to after the `dask.array` import.

2023-04-25 21:34 UTC, tomkralidis commented on msc_pygeoapi/provider/hrdps_zarr.py
> +    """
Space out all docstrings, i.e.:

```python
    """
    Helper function to make a where query string for
    nearest method when exact coordinates are not found

    :param first_query: original_dict of query
    :param new_query: transformed_dict of query

    :returns: where query string for use in .where()
    """
```

2023-04-25 21:34 UTC, tomkralidis commented on msc_pygeoapi/provider/hrdps_zarr.py
> +def _convert_subset_to_crs(new_lat: slice, new_lon: slice, crs):
Space out docstring.

2023-04-25 21:34 UTC, tomkralidis commented on msc_pygeoapi/provider/hrdps_zarr.py
> +    where_str = ''
I think we are trying to build up a query string here?  Possible alternative:

```python
    query_params = []

    for key in first_query.keys():
        if key not in new_query.keys():
            query_params.append(f'(self._data.{key}>={first_query[key].start})')
            query_params.append(f'(self._data.{key}<={first_query[key].stop})')

    query_string = ' & '.join(query_params)
    LOGGER.debug(f'Where query string: {query_string}')
    return query_string
```

2023-04-25 21:34 UTC, tomkralidis commented on msc_pygeoapi/provider/hrdps_zarr.py
> +def _make_where_str(first_query: dict, new_query: dict):
Provide a return type in the function annotation, so:


```python
def _make_where_str(first_query: dict, new_query: dict) -> str:
```

2023-04-25 21:34 UTC, tomkralidis commented on msc_pygeoapi/provider/hrdps_zarr.py
> +def _convert_subset_to_crs(new_lat: slice, new_lon: slice, crs):
Provide a return type in the function annotation, so:

```python
def _make_where_str(first_query: dict, new_query: dict) -> Tuple:
```

In this case you will have to add the following import:

```python
from typing import Tuple
```

2023-04-25 22:02 UTC, merged