update for sr3 configuration and callback
ECCC-MSC/msc-pygeoapi pull request #356
Opened 2024-11-25 13:20 UTC by RousseauLambertLP

update for sr3 configuration and callback

* replaced `message.py` and `file_.py` by `event_plugin.py` for the callback functions. Both cases are handled in a single file.
* `event_plugin.py` updated for callback instead of the previous plugin
* added `exchange xpublic` to all configuration
* updated the env var to point to the class in the callback (sr3) instead of the event file (sr2)
* reordered amqps configuration file for consistency

2024-11-25 13:30 UTC, tomkralidis requested changes

2024-11-25 13:30 UTC, tomkralidis commented on msc_pygeoapi/event/event_plugin.py
> +                LOGGER.error(f'Error handling message: {err}', exc_info=True)
`LOGGER.error(f'Error handling message: {err}')`

2024-11-25 13:30 UTC, tomkralidis commented on msc_pygeoapi/event/event_plugin.py
> +                filepath = os.path.join(msg['new_dir'], msg['new_file'])
`filepath = f"{msg['new_dir']}/{msg['new_file']}")` (and remove `os` import).

2024-12-30 20:01 UTC, Dukestep approved these changes

2024-12-31 14:41 UTC, merged